num_worker: 0
work_dir: ./work_dir/ntu120_hdgcn/cross-setup/joint_22_2d/

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: C:/Users/dooly/dataset/ntu120/NTU120_CSub_left_leg.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: C:/Users/dooly/dataset/ntu120/NTU120_CSub_left_leg.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.OPGCN.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d_hierarchy.Graph
  graph_args:
    labeling_mode: 'spatial'
    CoM: 20

#optim
weight_decay: 0.0004
base_lr: 0.1
warm_up_epoch: 5

# training
device: [0]
batch_size: 8
test_batch_size: 64
num_epoch: 100
nesterov: True
